### ISSUE TITLE
Vaultwarden 1.25.0 incompatible with debian buster 10

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [Masgalor/vaultwarden-packaging-obs#1]
See more info at https://github.com/dani-garcia/vaultwarden/issues/2549

It seems like Vaultwarden 1.25.0 needs GLIBC in version 2.29 or higher. Debian 10 only has 2.28, so it refuses to start.

Is there anything you can do or is this only fixable by the upstream-team?

Could you disable 1.25.0 in your Debian 10 repo (https://download.opensuse.org/repositories/home:/Masgalor:/Vaultwarden/Debian_10/) and republish 1.24.0 until this is fixed please?

Thanks!

**Comment by Masgalor** [comment]
Thank you for bringing this up.

It is not possible to build vaultwarden within Debian 10 because the available version of rust is too low.
The binary shipped with Debian 10 packages is actually built on Debian 11 thats why GLIBC 2.29 is reqquired.

I will reset the version to 1.24.0 and look for a way to crosscompile the Debian 10 binary with a lower GLIBC version.
This problem is not related to the upstream project, it is an error in my package.

**Comment by MatthiasKuehneEllerhold** [comment]
Thanks!

**Comment by Masgalor** [comment]
The package in the main-repo is now deactivated (I cant revert the revision for only one build-target).
While I am working on that issue, might take a little time, I set up another repo where you can get v1.24.0 again.

https://build.opensuse.org/package/show/home:Masgalor:Playground/vaultwarden

**Comment by MatthiasKuehneEllerhold** [comment]
Thanks! I've saved the .deb of the 1.24.0 from my cache and published in our own internal apt repo. With apt pinning set to 1.24.0 this should prevent the update until this is fixed.

**Comment by Masgalor** [comment]
Hey there.
Sorry for the long idle time, I have decided to rework the build recipes entirely so every binary can be built on their native platform.

This took a little time but I think it is done now.
I did not have the time to test every aspect of the new packages so they are experimental for now.
If you want to have a look you can do so, here https://build.opensuse.org/project/show/home:Masgalor:Vaultwarden_staging .
Be aware, experimental means, no built errors but also no function tests.

As soon as everything is proofed to work I will merge this repo into the stable one.

**Comment by Masgalor** [comment]
Since version 1.25.1 had some minor flaws (depending on the point of view...) we are now with 1.25.2 back on track.
Tests are done, all looks good to me, so both vaultwarden and the webvault are back to the stable channel.
